In [1]:
print("Fraud Detection Project")
print("Student: Bhavith Sai Kumar Reddy Poli")
print("ID: W25027212")

Fraud Detection Project
Student: Bhavith Sai Kumar Reddy Poli
ID: W25027212


# Fraud Detection Dissertation
## Student: Bhavith Sai Kumar Reddy Poli
### Module: LD7236

This project investigates machine learning techniques for financial fraud detection.

**Dataset:** PaySim + Kaggle Credit Card Fraud
**Models:** Random Forest, XGBoost, Neural Network

In [2]:
# This is a comment
name = "Bhavith"
age = 23
print("My name is " + name)
print("I am " + str(age) + " years old")

My name is Bhavith
I am 23 years old


In [3]:
import numpy as np


In [6]:
# Normal Python list
transactions = [200, 1500, 800, 9000, 50]

# NumPy array
transactions = np.array([200, 1500, 800, 9000, 50])
print(transactions*2)

[  400  3000  1600 18000   100]


In [7]:
import numpy as np

transactions = np.array([200, 1500, 800, 9000, 50])
print(transactions)

[ 200 1500  800 9000   50]


In [8]:
# Basic operations
print(transactions + 100)    # add 100 to every value
print(transactions * 2)      # multiply every value by 2
print(transactions.mean())   # average
print(transactions.max())    # highest
print(transactions.min())    # lowest
print(transactions.sum())    # total

[ 300 1600  900 9100  150]
[  400  3000  1600 18000   100]
2310.0
9000
50
11550


In [9]:
# Indexing — accessing specific values
print(transactions[0])    # first value
print(transactions[-1])   # last value
print(transactions[1:3])  # second and third

200
50
[1500  800]


In [10]:
# Shape — how many items
print(transactions.shape)  # (5,) means 5 items

(5,)


In [12]:
data = np.array([
    [200, 1, 44],
    [1500, 2, 12],
    [800, 3, 33],
    [9000, 4, 55],
    [50, 5, 22]
])

print(data)
print(data.shape)

[[ 200    1   44]
 [1500    2   12]
 [ 800    3   33]
 [9000    4   55]
 [  50    5   22]]
(5, 3)


In [16]:
transactions = np.array([200, 1500, 800, 9000, 50])

# Step 1 - see True/False
print(transactions > 1000)

# Step 2 - filter
print(transactions[transactions > 1000])

# Try different conditions
print(transactions[transactions < 500])   # below 500
print(transactions[transactions == 800])  # exactly 800

[False  True False  True False]
[1500 9000]
[200  50]
[800]
